### ISSUE TITLE
Post() got multiple values for argument 'data'

### ISSUE THREAD

**Issue by UkrainskyiRostyslav** [EGI-Federation/egicli#25]
```
Traceback (most recent call last):
  File "/usr/local/bin/egicli", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/egicli/endpoint.py", line 278, in token
    checkin_client_id, checkin_client_secret, checkin_refresh_token, checkin_url
  File "/usr/local/lib/python3.6/dist-packages/egicli/checkin.py", line 45, in refresh_access_token
    oidc_ep["token_endpoint"],
  File "/usr/local/lib/python3.6/dist-packages/egicli/checkin.py", line 32, in token_refresh
    r = requests.post(token_url, auth, data=refresh_data)
TypeError: post() got multiple values for argument 'data'
```

**Comment by enolfc** [comment]
Should be fixed by #26 (currently testing)

**Comment by enolfc** [comment]
It works now. please create a new refresh token if you still have issues with it.

**Comment by kstepanovdev** [comment]
@enolfc 
I'm sorry about this kwarg issue. I've created the PR to fix it, but as I can see you had fixed it.
