### ISSUE TITLE
Env vars for the endpoint commands are not working

### ISSUE THREAD

**Issue by andrea-manzi** [EGI-Federation/egicli#5]
#  Description of the issue
Running the egicli container, i noticed that the EGI_SITE and  OS_PROJECT_ID env vars are not taken into account when using the _endpoint_ commands

For instance 

```
root@13edf12cb07e:~# export EGI_SITE=INFN-CATANIA-STACK


root@13edf12cb07e:~# egicli --debug endpoint projects 
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): aai.egi.eu:443
DEBUG:urllib3.connectionpool:https://aai.egi.eu:443 "GET /oidc/.well-known/openid-configuration HTTP/1.1" 200 None
DEBUG:urllib3.connectionpFool:Starting new HTTPS connection (1): aai.egi.eu:443
DEBUG:urllib3.connectionpool:https://aai.egi.eu:443 "POST /oidc/token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): goc.egi.eu:443
DEBUG:urllib3.connectionpool:https://goc.egi.eu:443 "GET /gocdbpi/public/?method=get_site_list&certification_status=Certified HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): goc.egi.eu:443
DEBUG:urllib3.connectionpool:https://goc.egi.eu:443 "GET /gocdbpi/public/?method=get_service_endpoint&service_type=org.openstack.nova&monitored=Y HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.cloud.ifca.es:5000
DEBUG:urllib3.connectionpool:https://api.cloud.ifca.es:5000 "POST /v3/OS-FEDERATION/identity_providers/egi.eu/protocols/openid/auth HTTP/1.1" 201 495
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.cloud.ifca.es:5000
DEBUG:urllib3.connectionpool:https://api.cloud.ifca.es:5000 "GET /v3/auth/projects HTTP/1.1" 200 414
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sbgcloud.in2p3.fr:5000
DEBUG:urllib3.connectionpool:https://sbgcloud.in2p3.fr:5000 "POST /v3/OS-FEDERATION/identity_providers/egi.eu/protocols/openid/auth HTTP/1.1" 401 114
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sbgcloud.in2p3.fr:5000
DEBUG:urllib3.connectionpool:https://sbgcloud.in2p3.fr:5000 "POST /v3/OS-FEDERATION/identity_providers/egi.eu/protocols/oidc/auth HTTP/1.1" 401 197
Traceback (most recent call last):
  File "/usr/local/bin/egicli", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/egicli/endpoint.py", line 165, in projects
    unscoped_token, _ = get_unscoped_token(os_auth_url, access_token)
  File "/usr/local/lib/python3.8/site-packages/egicli/endpoint.py", line 85, in get_unscoped_token
    raise RuntimeError("Unable to get an scoped token")
RuntimeError: Unable to get an scoped token

```

In this case  an incorrect endpoint is invoked instead of the one from Catania

`DEBUG:urllib3.connectionpool:https://sbgcloud.in2p3.fr:5000 "POST /v3/OS-FEDERATION/identity_providers/egi.eu/protocols/oidc/auth HTTP/1.1" 401 197`

while if i pass the --site option it works as exptected

```
egicli --debug endpoint projects --site INFN-CATANIA-STACK
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): aai.egi.eu:443
DEBUG:urllib3.connectionpool:https://aai.egi.eu:443 "GET /oidc/.well-known/openid-configuration HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): aai.egi.eu:443
DEBUG:urllib3.connectionpool:https://aai.egi.eu:443 "POST /oidc/token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): goc.egi.eu:443
DEBUG:urllib3.connectionpool:https://goc.egi.eu:443 "GET /gocdbpi/public/?method=get_service_endpoint&service_type=org.openstack.nova&monitored=Y&sitename=INFN-CATANIA-STACK HTTP/1.1" 200 976
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): stack-server.ct.infn.it:35357
DEBUG:urllib3.connectionpool:https://stack-server.ct.infn.it:35357 "POST /v3/OS-FEDERATION/identity_providers/egi.eu/protocols/openid/auth HTTP/1.1" 201 495
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): stack-server.ct.infn.it:35357
DEBUG:urllib3.connectionpool:https://stack-server.ct.infn.it:35357 "GET /v3/auth/projects HTTP/1.1" 200 408
id                                Name      enabled    site
--------------------------------  --------  ---------  ------------------
00982464978c4b61a5f570e315251f02  TRAINING  True       INFN-CATANIA-STACK
```

same for endpoint env command

```
root@13edf12cb07e:~# export OS_PROJECT_ID=00982464978c4b61a5f570e315251f02

root@13edf12cb07e:~# egicli endpoint env
Usage: egicli endpoint env [OPTIONS]
Try "egicli endpoint env --help" for help.

Error: Missing option "--project-id".
```

while when using the option --project-id is working fine

```
egicli endpoint env --project-id=00982464978c4b61a5f570e315251f02
# environment for INFN-CATANIA-STACK
export OS_AUTH_URL="https://stack-server.ct.infn.it:35357/v3"
export OS_AUTH_TYPE="v3oidcaccesstoken"
export OS_IDENTITY_PROVIDER="egi.eu"
export OS_PROTOCOL="openid"
...
```

**Comment by andrea-manzi** [comment]
for instance i see here 

https://github.com/EGI-Foundation/egicli/blob/master/egicli/endpoint.py#L154

there is no default value taken from the env var

**Comment by andrea-manzi** [comment]
here the env var is mispelled
https://github.com/EGI-Foundation/egicli/blob/master/egicli/endpoint.py#L277

will do a PR:-)
